services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6414
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: guilhermevianna445/rolatrama:api-dev
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:6414@db:5432/rolatrama
    ports:
      - "3000:3000"
    restart: always

volumes:
  db_data: